### ISSUE TITLE
Example of useState

### ISSUE THREAD

**Issue by fessacchiotto** [u3u/vue-hooks#16]
Hi! Thanks for your code. Is it possible to have an example of usage of the `useState` hook?

**Comment by u3u** [comment]
Hello! You can output the return value of the hook in the `setup` function.

The usage of the `useState` hook is exactly the same as the usage of [`mapState`](https://vuex.vuejs.org/api/#mapstate) (the same parameters)

The only difference is that the return value of `useState` is the [`Wrapper<any>`](https://github.com/vuejs/vue-function-api/blob/1d532fe684e2343973ae46fc3ef93e497e6514b1/src/wrappers/index.ts#L5-L7) dictionary. For each item in the dictionary, you need to use `.value` to get its actual value.

```tsx
import { createComponent } from 'vue-function-api';
import { useState } from '@u3u/vue-hooks';

export default createComponent({
  setup() {
    const { count } = useState(['count']);
    console.log(count.value);

    return { count };
  },
});
```

I will provide complete documentation and examples as soon as possible.

**Comment by fessacchiotto** [comment]
Thank you!

**Comment by u3u** [comment]
Welcome to visit: <https://vue-hooks.netlify.com>
