### ISSUE TITLE
Getter does not accept payload

### ISSUE THREAD

**Issue by clemir-legon** [u3u/vue-hooks#185]
Hello, I am trying to send a payload through the Getter but it sends me an error in the console where it tells me that it is not a function. How could I send a payload to filter store data please.

As follows
`getters.myGetter("filter")`

**Comment by anwaar931** [comment]
Yup, want to pass a value in getter but can't.

**Comment by anwaar931** [comment]
@CRLL19-81  Just played with it a little bit, you can do it like,

`getters.myGetter.value('filter')`

Worked for me.

**Comment by clemir-legon** [comment]
@anwaar931 you are absolutely right, thank you very much, excuse my ignorance
