### ISSUE TITLE
vue-function-api + Vue-hooks + spread operator examples

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [u3u/vue-hooks#23]
**Configuring our setup()**
It is a good idea to identify each logical part of the setup component. For this we can take as reference the structure of the store, where we have separated the _state , mutations, actions, 
getters_ ...

As you know, Vuex uses a single state tree, that is, this single object contains all its application level status and serves as the "single source of truth." This also means that you will usually only have one store for each application. A single status tree facilitates the location of a specific state and allows us to take snapshots of the current state of the application for debugging purposes.

We can conclude that we can maintain the concept of single state tree, which will help us understand our code logic as the project grows.

**What is the spread operator?**
*The spread operator allows an expression to be expanded in situations where multiple arguments (function calls) or multiple elements (literal arrays) are expected.*

```javascript
<script>
  import {onCreated} from 'vue-function-api';
  import {useState , useActions} from '@u3u/vue-hooks'

  export default {
    setup(){
      const state = { 
        ...useState(['items' , 'isLoading'])
      }
      const actions = { 
        ...useActions(['GET_ITEMS'])
      };
      onCreated(() =>{
        actions.GET_ITEMS();
      });

      return{
        items: state.items,
        isLoading: state.isLoading
      }  
    },
  };
</script>
```

**Comment by u3u** [comment]
Hi, you can refer to this example:

[![Edit Vue Hooks Examples](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-66f2o?expanddevtools=1&fontsize=12&module=%2Fsrc%2FApp.vue)

```vue
<script>
import { createComponent } from 'vue-function-api';
import { useState, useGetters, useMutations, useActions } from '@u3u/vue-hooks';

export default createComponent({
  name: 'App',

  setup() {
    const state = {
      ...useState(['count']),
    };

    const getters = {
      ...useGetters(['plusOne']),
    };

    const mutations = {
      ...useMutations(['increment', 'decrement']),
    };

    const actions = {
      ...useActions(['incrementAsync', 'decrementAsync']),
    };

    return {
      ...state,
      ...getters,

      state,
      getters,
      mutations,
      actions,
    };
  },

  render() {
    const { count, plusOne, state, getters, mutations, actions } = this;
    console.log(count); // number
    console.log(plusOne); // number
    console.log(state.count); // ComputedWrapper
    console.log(getters.plusOne); // ComputedWrapper

    return (
      <div id="app">
        <div>count(state): {count}</div>
        <div>plusOne(getters): {plusOne}</div>
        <button onClick={() => mutations.increment()}>increment</button>
        <button onClick={() => mutations.decrement()}>decrement</button>
        <button onClick={() => actions.incrementAsync()}>incrementAsync</button>
        <button onClick={() => actions.decrementAsync()}>decrementAsync</button>
      </div>
    );
  },
});
</script>

```

**Comment by ChrisMichaelPerezSantiago** [comment]
Regard @u3u ,

I recommend if you can, add that type of structure (example) as documentation for official use.

**Comment by u3u** [comment]
Yes, I am writing documentation and examples.
I usually work very busy, only available on weekends. 😅

**Comment by u3u** [comment]
Welcome to visit: <https://vue-hooks.netlify.com>
